DROP DATABASE IF EXISTS nelson_laluna;
CREATE DATABASE nelson_laluna;
USE nelson_laluna; 

CREATE TABLE articulos(
  id_articulo int AUTO_INCREMENT,
  articulo varchar(127),
  descripcion varchar(255),
  grupo varchar(255),
  precio float,
  PRIMARY KEY(id_articulo)  
  );
SELECT * FROM articulos;
CREATE TABLE ingredientes(
  id_ingrediente int AUTO_INCREMENT,
  ingrediente varchar(127),
  precio float,
  PRIMARY KEY(id_ingrediente),
  UNIQUE  (ingrediente)  
  );
CREATE  TABLE agregan(
  id_articulo int,
  id_ingrediente int,
  cantidad int DEFAULT 1,
  PRIMARY KEY (id_ingrediente,id_articulo),
  FOREIGN KEY (id_articulo) REFERENCES articulos(id_articulo),
  FOREIGN KEY (id_ingrediente) REFERENCES ingredientes(id_ingrediente)
  );
CREATE TABLE locales(
  id_local int AUTO_INCREMENT,
  establecimiento varchar(127),
  localidad varchar(255),
  PRIMARY KEY(id_local),
  UNIQUE(establecimiento)
  );
CREATE TABLE servicios(
  id_servicio int AUTO_INCREMENT,
  servicio varchar(127),
  PRIMARY KEY (id_servicio),
  UNIQUE(servicio)
  );
CREATE TABLE venden(
  id_articulo int,
  id_servicio int,
  id_local int,
  precio float,
  PRIMARY KEY (id_articulo,id_servicio,id_local),
  FOREIGN KEY(id_articulo) REFERENCES articulos (id_articulo),
  FOREIGN KEY(id_servicio) REFERENCES servicios (id_servicio),
  FOREIGN KEY(id_local) REFERENCES locales (id_local)  
  );
INSERT locales (establecimiento,localidad)
  VALUES ("La Luna","Plaza de la constitución,Reinosa"),
  ("El Chiringuito","Plaza de la constitución,Reinosa");
INSERT servicios(servicio)
  VALUES ('Reparto a domicilio'), ('Recogida en local');
INSERT INTO articulos VALUES
(1, 'Margarita', 'jamón york', 'Pizzas', 8),
(2, 'Reina', 'jamón york y champiñones', 'Pizzas', 9.5),
(3, 'Bolognesa', 'carne bolognesa, pimiento rojo y cebolla', 'Pizzas', 9.5),
(4, 'Bolognesa con salsa barbacoa', 'carne bolognesa, pimiento rojo, cebolla y salsa barbacoa', 'Pizzas', 9.5),
(5, 'De la Huerta', 'espinacas con besamel', 'Pizzas', 9.5),
(6, 'Romana', 'jamón serrano', 'Pizzas', 9.5),
(7, 'Vegetal', 'alcachofas, pimiento, espárragos y champiñones', 'Pizzas', 9.5),
(8, 'Cuatro Quesos', 'mozzarella, emmental, manchego y azul', 'Pizzas', 9.5),
(9, 'Tropical', 'jamón york y piña', 'Pizzas', 9.5),
(10, 'La Luna', 'bonito y besamel', 'Pizzas', 9.5),
(11, 'Atómica', 'pepinillo, guindilla y aceituna', 'Pizzas', 9.5),
(12, 'Elena', 'bacon, pimiento verde y cebolla', 'Pizzas', 9.5),
(13, 'De pollo', 'guindilla y pollo', 'Pizzas', 9.5),
(14, 'Campurriana', 'jamón york, bacon y chorizo', 'Pizzas', 9.5),
(15, 'Cuatro estaciones', 'marinera, campurriana, 4 quesos y reina', 'Pizzas', 9.5),
(16, 'Alemana', 'bacon, salchicha, pimiento y cebolla', 'Pizzas', 9.5),
(17, 'Calzone', 'empanada de carne o pescado', 'Pizzas', 9.5),
(18, 'Calzone de pollo', 'empanada de pollo con besamel', 'Pizzas', 9.5),
(19, 'Strombolli', 'carne, chorizo, pimiento, champiñón y cebolla', 'Pizzas', 9.5),
(20, 'Rústica', 'lomo, pimiento rojo y ajo', 'Pizzas', 9.5),
(21, 'Serrana', 'jamón serrano, tomate natural y huevo', 'Pizzas', 9.5),
(22, 'Marinera', 'bonito y langostinos', 'Pizzas', 9.5),
(23, 'Frutos del mar', 'bonito, langostinos y pulpo', 'Pizzas', 9.5),
(24, 'Tierra y mar', 'bacon, salchicha, langostinos, cebolla y ajo', 'Pizzas', 9.5),
(25, 'Barbacoa', 'pollo y salsa barbacoa', 'Pizzas', 9.5),
(26, 'Capricho', 'jamón york, salchicha frankfurt y bacon', 'Pizzas', 9.5),
(27, 'Carbonara', 'nata, bacon y pimienta', 'Pizzas', 9.5),
(28, 'De Morcilla', 'morcilla de Burgos, pimiento y cebolla', 'Pizzas', 9.5),
(29, 'De Berenjenas', 'jamón york, berenjena, queso azul, tomate, champiñones y aceitunas', 'Pizzas', 9.5),
(30, 'Especial de la Casa', 'queso philadelphia, pollo, salchicha, cebolla, bacon, maiz y aceitunas', 'Pizzas', 9.5),
(31, 'La Roja', 'salsa Roquefort, champiñones, pimiento rojo y carne', 'Pizzas', 9.5),
(32, 'De Queso de cabra', 'champiñones, bacon, cebolla y queso de cabra', 'Pizzas', 9.5),
(33, 'Ibéricos', 'queso Roquefort, champiñones, aceitunas, lomo ibérico, jamón ibérico bellota', 'Pizzas', 9.5),
(34, 'Pechuga de Pavo', 'queso Roquefort, pimiento verde, champiñones', 'Pizzas', 9.5),
(35, 'Verde', 'lechuga, tomate, cebolla y aceitunas', 'Ensaladas', 4.5),
(36, 'Mixta', 'lechuga, tomate, cebolla, espárragos, huevo, bonito y aceitunas', 'Ensaladas', 7),
(37, 'De Queso', 'queso, mozzarella, tomate, alcaparras, aceitunas y anchoas', 'Ensaladas', 7),
(38, 'Rosa', 'ensalada mixta con saslsa rosa', 'Ensaladas', 7),
(39, 'De la Casa', 'lechuga, tomate, bonito, aceitunas, espárragos, huevo, queso, ajo, manzana, cebolla y zanahoria', 'Ensaladas', 7.5),
(40, 'E.Tropical', 'lechuga, jamón york, piña, frutas de temporada, zanahoria, boas de mar, salsa rosa y aceituna', 'Ensaladas', 7.5),
(41, 'E.La Luna', 'lechuga, tomate, queso azul, anchoas y alcaparras', 'Ensaladas', 7.5),
(42, 'E.De pollo', 'lechuga, pollo, maiz, pasas, manzana, aeitunas, zanahoria, y salsa rosa', 'Ensaladas', 8),
(43, 'De Pasta', 'fetuccini, lechuga, salsa tártara o rosa', 'Ensaladas', 8),
(44, 'Periñaca', 'lechuga, tomate, cebolla, huevo, espárragos, bonito, jamón york, patata cocida, gambas y aceitunas', 'Ensaladas', 8),
(45, 'Imperial', 'cogollos de lechuga, anchoas, pimiento, bonito y aceitunas', 'Ensaladas', 8),
(46, 'De fruta', 'lechuga, naranja, manzana, pasas, aceitunas, piña y fruta de temporada', 'Ensaladas', 8),
(47, 'De pasta farfalle', 'lechuga, lacitos de pasta, maiz, jamón york y salsa tártara o rosa', 'Ensaladas', 8),
(48, 'E.De queso de cabra', 'queso de cabra, manzana, pasas, frutos secos y anchoas', 'Ensaladas', 8),
(49, 'De ventresca', 'lechuga, tomate, cebolla, anchoas, cangrejo de mar, ventresca y aceitunas negras', 'Ensaladas', 9),
(50, 'Pudding de cabracho', '', 'Entrantes', 8),
(51, 'Alcachofas La Luna', '', 'Entrantes', 8),
(52, 'Huevos al jamón', '', 'Entrantes', 8),
(53, 'Cocktail de marisco', '', 'Entrantes', 8),
(54, 'Pimientos con anchoas', '', 'Entrantes', 8),
(55, 'Revuelto de langostinos y champiñones', '', 'Entrantes', 10),
(56, 'Pan de ajo', '', 'Entrantes', 3),
(57, 'Solomillo al Rocheford', '', 'Carnes', 12),
(58, 'Solomillo a la Pimienta', '', 'Carnes', 12),
(59, 'Filete de ternera, huevo y patatas', '', 'Carnes', 10),
(60, 'Chuleta de ternera, huevo y patatas', '', 'Carnes', 12),
(61, 'Alitas de pollo con salsa barbacoa y patatas', '', 'Carnes', 8),
(62, 'Spaguetti al Ajo', '', 'Pasta', 6.5),
(63, 'Spaguetti Pomodoro', 'chorizo, queso y tomate', 'Pasta', 7),
(64, 'Spaguetti Carbonara', 'nata, huevo, pimienta, bacon y guindilla', 'Pasta', 7),
(65, 'Spaguetti Fiorentina', 'maiz, bonito y mahonesa', 'Pasta', 7),
(66, 'Spaguetti Gamberone', 'langostinos, ajo y aceite de oliva', 'Pasta', 8),
(67, 'Spaguetti Bolognesa', 'tomate, carne y queso', 'Pasta', 7),
(68, 'Spaguetti Cuatro quesos', 'mozzarella, emmental, manchego y azul', 'Pasta', 7),
(69, 'Spaguetti Negros', 'champiñones, gambas, nata, pimienta y queso azul', 'Pasta', 8.5),
(70, 'Lasaña Bolognesa', 'carne, tomate, queso y besamel', 'Pasta', 7),
(71, 'Lasaña de la Huerta', 'espinacas, carne y besamel', 'Pasta', 7),
(72, 'Ravioli Piamontesa', 'nata, tomate y pimienta', 'Pasta', 7),
(73, 'Fetuccini con langostinos y gulas', '', 'Pasta', 9),
(74, 'Fetuccini con Gambas', '', 'Pasta', 8),
(75, 'Fetuccini Bolognesa', 'carne tomate y queso', 'Pasta', 7),
(76, 'Fetuccini Verdes', 'nata, queso roqueford, pimienta y nueces', 'Pasta', 7),
(77, 'Canelones', 'carne queso tomate y besamel', 'Pasta', 7),
(78, 'Trio de pasta', 'lasaña boloñesa, ravioli piamontea y canelones', 'Pasta', 10),
(79, 'Agua', '', 'Bebidas', 1),
(80, 'Agua grande', '', 'Bebidas', 2.5),
(81, 'Cerveza', '', 'Bebidas', 2.5),
(82, 'Latas', '', 'Bebidas', 2),
(83, 'Rioja del año', '', 'Vinos', 6),
(85, 'Vino joven', '', 'Vinos', 6),
(86, 'Sangria', '', 'Vinos', 6),
(87, 'Mateus Rose', '', 'Vinos', 10),
(88, 'Peñascal', ' ', 'Vinos', 10),
(89, 'Lambrusco', ' ', 'Vinos', 8),
(90, 'Canei rosado / blanco', ' ', 'Vinos', 10),
(91, 'Vinos de Rioja', ' ', 'Vinos', 12),
(92, 'Vinos de Ribera', ' ', 'Vinos', 14),
(93, 'Vinos de Ribera (Crianza)', ' ', 'Vinos', 18),
(94, 'Mousse de limón', ' ', 'Postres', 3.5),
(95, 'Mousse de plátano', ' ', 'Postres', 3),
(96, 'Mousse de chocolate', ' ', 'Postres', 3.5),
(97, 'Tarta de queso y moras', ' ', 'Postres', 3.5),
(98, 'Tarta de chocolate', ' ', 'Postres', 3.5),
(99, 'Tarta de crema de queso', ' ', 'Postres', 3.5),
(100, 'Tarta de Tiramisú', ' ', 'Postres', 3.5),
(101, 'Pudding de nueces', ' ', 'Postres', 3.5);